// Code generated by "stringer --type operator"; DO NOT EDIT.

package effe

import "strconv"

const _operator_name = "IntersectionUnaryNegationPercentExponentiationMultiplicationDivisionAdditionSubtractionConcatenationEqualityGreaterThanLessThanGreaterThanOrEqualLessThanOrEqualInequality"

var _operator_index = [...]uint8{0, 12, 25, 32, 46, 60, 68, 76, 87, 100, 108, 119, 127, 145, 160, 170}

func (i operator) String() string {
	if i < 0 || i >= operator(len(_operator_index)-1) {
		return "operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _operator_name[_operator_index[i]:_operator_index[i+1]]
}
